export const START_FLIGHT_CALL = "START_FLIGHT_CALL"
export const FLIGHT_CALL_FAILED = "FLIGHT_CALL_FAILED"

export const CREATE_FLIGHT = 'CREATE_FLIGHT'
export const CREATE_FLIGHT_SUCCESS = 'CREATE_FLIGHT_SUCCESS'

export const GET_ADMIN_FLIGHTS = 'GET_ADMIN_FLIGHTS'
export const GET_ADMIN_FLIGHTS_SUCCESS = 'GET_ADMIN_FLIGHTS_SUCCESS'

export const GET_FLIGHT = 'GET_FLIGHT'
export const GET_FLIGHT_SUCCESS = 'GET_FLIGHT_SUCCESS'

export const DELETE_FLIGHT = 'DELETE_FLIGHT'
export const DELETE_FLIGHT_SUCCESS = 'DELETE_FLIGHT_SUCCESS'

export const BOOK_FLIGHT = 'BOOK_FLIGHT'
export const BOOK_FLIGHT_SUCCESS = 'BOOK_FLIGHT_SUCCESS'

export const GET_BOOKED_FLIGHTS = 'GET_BOOKED_FLIGHTS'
export const GET_BOOKED_FLIGHTS_SUCCESS = 'GET_BOOKED_FLIGHTS_SUCCESS'

export const FLIGHT_DISMISS_ERROR = 'FLIGHT_DISMISS_ERROR'